// Bundle the fixed local preload dependencies using only Node's standard library.
// Sandboxed preloads cannot require application files at runtime.
const fs = require('node:fs');
const path = require('node:path');
const { createConfigSchema } = require('../electron/config-schema');
const { createBridgeContract } = require('../electron/bridge-contract');
const root = path.resolve(__dirname, '..');
function buildPreload() {
    let source = fs.readFileSync(path.join(root, 'electron/preload-game.js'), 'utf8');
    for (const [name, file, factory] of [
        ['createConfigSchema', 'config-schema', createConfigSchema],
        ['createBridgeContract', 'bridge-contract', createBridgeContract],
    ]) {
        const declaration = `const { ${name} } = require('./${file}');`;
        if (source.split(declaration).length !== 2) throw new Error(`Expected exactly one ${file} import`);
        source = source.replace(declaration, `const ${name} = ${factory.toString()};`);
    }
    const bundled = '// Generated by scripts/build-preload.cjs; edit source modules.\n' + source;
    const destination = path.join(root, 'electron/generated/preload-game.js');
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, bundled);
    return destination;
}
if (require.main === module) console.log(path.relative(root, buildPreload()));
module.exports = { buildPreload };
